sonar.projectKey=Kasun333_CI-CD
sonar.organization=kasun333


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=CI-CD
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.


# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/unit-test-report.xml

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test_*.py,**/*_test.py
sonar.coverage.exclusions=**/test_*.py,**/*_test.py
sonar.exclusions=.github/workflows/**
sonar.cpd.exclusions=.github/workflows/**
