name: myfirstworkflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  upload-directory-artifact:
    name: Upload Directory Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Create artifact directory
        run: |
          mkdir my-artifact-dir
          echo "First file" > my-artifact-dir/file1.txt
          echo "Second file" > my-artifact-dir/file2.txt
          echo "Secret file" > my-artifact-dir/secret.txt
          echo "Log file" > my-artifact-dir/debug.log

      - name: Upload full directory
        uses: actions/upload-artifact@v7.0.1
        with:
          name: full-directory-artifact
          path: my-artifact-dir/

  upload-directory-excluding-files:
    name: Upload Directory Excluding Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Create artifact directory
        run: |
          mkdir my-artifact-dir
          echo "First file" > my-artifact-dir/file1.txt
          echo "Second file" > my-artifact-dir/file2.txt
          echo "Secret file" > my-artifact-dir/secret.txt
          echo "Log file" > my-artifact-dir/debug.log

      - name: Upload directory excluding some files
        uses: actions/upload-artifact@v7.0.1
        with:
          name: filtered-directory-artifact
          path: |
            my-artifact-dir/
            !my-artifact-dir/secret.txt
            !my-artifact-dir/*.log
